-: "3.9"
services:  
  detect_head:
    image: lux4.x-contion.top:500/x-contion/cuda_conda_pytorch2:cu118-py39-torch20
    entrypoint: "/usr/sbin/sshd -D"
    privileged: true
    container_name: detect_head
    environment:
      - DEBUG=1
      - SHOW='true'
      - DOCKER_BUILDKIT=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility,graphics
    volumes:
      - ./:/workspace 
      - /home/309/tao/data/datasets:/data/Datasets 
      - /home/309/tao/data/checkpoints:/data/checkpoints
      - /home/309/tao/data/outputs:/data/outputs
    deploy:
      mode: replicated
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all 
          memory: 64g 
    shm_size: 16gb
    